= DNP3

OpenPLC supports running as a DNP3 outstation (server) using the OpenDNP3 library
provided by Automatak. This chaper covers how to configure DNP3 support in OpenPLC
and ends with an example program to test things out yourself.

IMPORTANT: DNP3 is not implemented on the Windows platform.

== DNP3 Basics

DNP3 is a robust communication protocol often used where a device is to be monitored
or controlled by a master. The protocol is commonly usedb by electric and water utilities.
DNP3's integrity is achieved through extensive use of cyclic redundancy check codes and
unlike Modbus, supports unsolicited messages (events) that reduce or eliminate the
need for polling-based approaches.

DNP3 is primarily concerned with data points. Each data point is describe by a type and
and index. (The astute reader will note that a type in DNP3 has a different meaning,
however, I will use this meaning to relate to the domain of the software engineer.)
The type is normally descriptive of a physical process that generates the value,
and helps to think in terms of electronics in understanding DNP3 types.

| Type    | Usage |
|---------|-------|
| Digital |       |
| Analog  |       |

Each 
