= Extending the OpenPLC Runtime

This chapter will get you into the guts of the OpenPLC runtime so that you can extend
it's capabilities to add the ability to communicate using different protocols. This chapter
beings by explaining the concept of glue variables followed by demonstrating how to add
your own custom protocol.

== Glue Variables

The OpenPLC runtime provides bindings between communication protocols, such as Modbus
or DNP3, and the program code that was described using IEC 61131-3 syntax and
converted to C using MATIEC.

The subset of variables in the program code that have a defined location are available
for gluing. Other variables in the program code are internal to the program and in general
may be entirely unavailable due to compiler optimizations.

OpenPLC allows your application to use multiple protocols simultaneously. The API provides
capabilities to enumerate located variables with their properties, so that they can be
glued to a particular protocol implementation. The API provides futher capabilities to
ensure efficient and exclusive access to variables and maintain safety.

Glue variables structures are code generated at compile time for your application using
the glue generation application and information about located variables from your application.
Glue variables are associated with particular protocols at runtime according to mapping
information that is provided as external configuration information.

INSERT DIAGRAM OF THE PROCESS
